### ISSUE TITLE
Multiple values in the Purpose column (sheets)

### ISSUE THREAD

**Issue by zoka123** [forikal-uk/gsheet-to-xml#1]
Purpose column in the sheet is a single cell and therefore single string value.
Purposes elements in the XML are array of Purpose elements.

If there are multiple values in the single cells, how are they delimited?
Comma separated values?

**Comment by forikal-uk** [comment]
Thanks for raising this issue. 

Yes. The XML is able to cater for more than one Purpose. However, our client interface (the sheets) do not document this feature to the clients. For now, we never have more than one Purpose.

We have a Google Apps script which validates the Sheet and ensures that Purpose matches the correct format (an enumerated list)

So, we take the one value from Purpose column and place it as a "collection of one Purpose" in the Purposes element of the XML.
