### ISSUE TITLE
XML structure for empty elements

### ISSUE THREAD

**Issue by zoka123** [forikal-uk/gsheet-to-xml#3]
[XML sample](https://github.com/forikal-uk/xml-authoring-project/blob/master/src/Inventory/Inventory.xml) is inconsistent when it comes to empty elements

`<AdditionalKNumbers></AdditionalKNumbers>` vs `<PurposeOther />`

Which syntax should be used for empty elements?

**Comment by forikal-uk** [comment]
Thanks for raising this. 

I think it does not matter which method is used. 

I believe that the `<AdditionalKNumbers></AdditionalKNumbers>` is the preferred method.

 i.e "an empty open and close tag" and not using self-closing elements.

At some point we could refactor to encapsulate "the creation of empty elements" into a method. Then, if we need to change the strategy in an emergency we can do it in one place. 

However, I agree the inconsistency can be confusing. So, I will update the XML to make this more consistent to avoid confusion in the future.

**Comment by zoka123** [comment]
When XML is outputted there is param `LIBXML_NOEMPTYTAG` that does it, i.e. `$dom->saveXML(null, LIBXML_NOEMPTYTAG);`

If you  want to change that behavior later simply omit the second param from the `saveXML` method

**Comment by john-arcus** [comment]
Great sounds good. Thanks.

**Comment by forikal-uk** [comment]
Ok that is interesting. Thanks.
