### ISSUE TITLE
Feedback for ignored files/tabs

### ISSUE THREAD

**Issue by zoka123** [forikal-uk/gsheet-to-xml#4]
Specification says:

> If a Google Sheet's tab is named foo_, then it is assumed to be 'private' and should be explicitly ignored, but it should be noted (in any feedback) that it was ignored.

and
> If a file is called foo_, then it is assumed to be 'private' and should be explicitly ignored, but it should be noted (in any feedback) that it was ignored

How should system note the feedback?
It can't be message in the output as it would disrupt the XML

**Comment by zoka123** [comment]
I suggest we leave `@todo` comment and implement feedback console messages once XML is written directly to file instead on STD_OUT.

Then you can pipe the output to some log file and see which tabs are skipped

**Comment by forikal-uk** [comment]
Thanks.
