### ISSUE TITLE
Please reflect Sheet name in Xml Attributes too.

### ISSUE THREAD

**Issue by forikal-uk** [forikal-uk/gsheet-to-xml#8]
# Steps to recreate

I [added some TestFixture files to use as samples to test on](https://github.com/forikal-uk/gsheet-to-xml/issues/6#issuecomment-393723262).

[I ran the gsheet-to-xml command supplying the Drive folder url](https://github.com/forikal-uk/gsheet-to-xml/issues/6#issuecomment-393723785). 

The xml is streamed to a STD_OUT ([see it here](https://github.com/forikal-uk/gsheet-to-xml/issues/6#issuecomment-393723785))

# What happens

When I try to compare the resulting Xml with the TestFixture files I find it hard to work out which snippet of Xml related to which File. I notice the Tab names are really handy. I was almost prompted to go and update my TestFixture tab names to reflect the sheet name in them to make my life easier.

# What is expected

So, now it would be great if the Xml attribute could, not only, reflect the sheet url, and tab name, but also reflect the Sheet **Name** (escaped properly for Xml attributes) if possible.

This would make manual testing of the tool against known TestFixture files a bit easier.

---------

**Comment by forikal-uk** [comment]
@zoka123 I have added a request for improvement to make testing easier.

**Comment by zoka123** [comment]
@forikal-uk 

I've create PR with improvements
https://github.com/forikal-uk/gsheet-to-xml/pull/9

Inventory element now looks like this:

```
<Product>
    <Inventory src-sheet="File1.xlsx" src-sheet-url="https://docs.google.com/spreadsheets/d/1-3FbTkn7VSbfRmiOgp_IDBBKm4FJ3HVNs9kEf64ZWOQ/" src-tab="Sheet3">
```

Note that I've added `src-sheet` with spreadsheet name, `src-sheet-url` with the spreadsheet URL, keeping `src-tab` with sheet/tab name.

I think this is now quite descriptive

**Comment by forikal-uk** [comment]
Thanks. @zoka123 . That is great.
